### ISSUE TITLE
Option for modifying the download command?

### ISSUE THREAD

**Issue by Wurzelmann** [eikek/meth#1]
I was wondering how I could modify the download command in order to include an user agent. Simply adding the "--user-agent" directive in the meth.conf did not work unfortunately.

**Comment by eikek** [comment]
How did you  specifiy this option? By default, the `curl` external program is used. I think if you put this in the config
```
meth {
  download-cmd {
    options = [ "--user-agent", "mozilla" "-L", "-o", "%[outfile]", "%[url]" ]
  }
}
```
It should run curl with all these options.

**Comment by Wurzelmann** [comment]
Ah, you're right, that seems to do the trick! I tried adding the options to the "curl" parameter right above this, which resulted in multiple errors. Thank you!
