### ISSUE TITLE
[feature request]: download log for downloaded media

### ISSUE THREAD

**Issue by Wurzelmann** [eikek/meth#2]
It would be great to have a download log similar to the one youtube-dl provides which "records" downloaded media and does not download it again, even if the media file is deleted/moved away. Currently meth re-downloads media which has been deleted or moved, but it would be very handy if it looked up already-downloaded files in a file and does not get them again.

**Comment by eikek** [comment]
That's a nice idea, thanks!

**Comment by Wurzelmann** [comment]
It would make this piece of software so much better, because of the automated things one could do via cron jobs and such. :-)

**Comment by eikek** [comment]
Yes you're right; I could use that feature too :-)

**Comment by Wurzelmann** [comment]
Works like a charm, thank you!

**Comment by eikek** [comment]
You're welcome :)
