### ISSUE TITLE
[feature request] Media title as filenames

### ISSUE THREAD

**Issue by Wurzelmann** [eikek/meth#3]
Is it possible to rename downloaded files according to their title as shown during searches, e.g.

title
`Tatort: Wie einst Lilly`--> `Tatort: Wie einst Lilly.mp4`

instead of

`http://hrardmediathek-a.akamaihd.net/video/as/tatort/2017_11/171130201733_2017-11-29_20-55-02_Tatort__Wie_einst_Lilly_1280x720-50p-5000kbit.mp4` ?

Thanks in advance!

**Comment by eikek** [comment]
Not sure, if I understand. Doesn't the `--pattern` option work? It is not very well documented, [this](https://github.com/eikek/meth#download) of the README tells a little. You can specify the file name via a pattern and various replacements are available. I think in your example `meth download --pattern "%[title]" …` should work. Also, `meth download --help` shows the available options.

**Comment by Wurzelmann** [comment]
First, I'm sorry about the README, I just didn't see this part, but I cannot get it to work.

I tried something like `meth download --pattern "%[title]" Tatort` but the downloaded files are not named like the title in the query, but something like `tatort_zuzenhausen-was_werder_zur_drohnen-spionage_sagt.mp4`

**Comment by eikek** [comment]
Ah yes, the names are still normalized to avoid invalid file names. That is currently not possible to change via options. But it is not hard to add/change.

**Comment by eikek** [comment]
If the normalization could be switched off via an option, would that work for you?

**Comment by Wurzelmann** [comment]
I'm not sure I understand correctly, but it sounds like what I have in mind, yes. Thanks in advance!

**Comment by eikek** [comment]
Currently, the filenames are generated from title, subject etc but then changed to contain ascii characters only. Anyways, I think that's good to have the option :) Thanks for the input! You can try the master branch in a minute or two.

**Comment by Wurzelmann** [comment]
I cannot get this to work... I added `normalize = False` to my meth config, but it does not work. :-( Am I doing something wrong?

**Comment by eikek** [comment]
Ah sorry, it is not a config thing; you'll need to add this option to the download command:
```
meth download --normalize false …
```
If you run `meth download --help` (it's not documented:() you'll see a little options overview.

**Comment by Wurzelmann** [comment]
Aaaaah, I see! Thanks, working perfectly! <3
