### ISSUE TITLE
Updating movie list at beginning of bash script does not seem to work

### ISSUE THREAD

**Issue by Wurzelmann** [eikek/meth#6]
I created a short bash script in order to execute meth periodically via a cron job and set `auto-download = false` in order to not update the file with every new line of the script.

Example lines in the script:

```
meth download --normalize false --pattern "%[date]_%[subject]_%[title]" 'Universum >40' station:orf
meth download --normalize false --pattern "%[date]_%[subject]_%[title]" 'Am Schauplatz' station:orf
```
The first line in the script is

`meth update` and I expected a movie list update and then queries/downloads with the new and updated file but instead there are these info messages before every download saying

`Info: There is a newer filmlist version available.`

I do not understand why I get those messages, surely the movie list file should up to date when the other meth queries start? It says so at the beginning:

```
Downloading movie list… ok
Unpacking movie list file… ok
```

Am I doing this wrong?

**Comment by eikek** [comment]
I think you are doing it just right. I also think, that the movie list is up to date and that this info message simply is wrong. This is a bug in meth. I have to investigate why it now reports this false message.

Just a side note: you could combine both queries into one to at leat reduce the noise a bit: 
```
meth '(| (& universum >40 station:orf) (& am schauplatz station:orf))'
```
Thank you for reporting this!

**Comment by Wurzelmann** [comment]
Thank you for this, if those warnings are just a bug, I'm going to ignore them.

**Comment by eikek** [comment]
I'm leaving this open, if you don't mind. Not sure when I have time to look into this, but it's an open bug right now :)

**Comment by Wurzelmann** [comment]
Sure, thanks. :-)
