### ISSUE TITLE
ORF titles are not being handled properly

### ISSUE THREAD

**Issue by Wurzelmann** [eikek/meth#8]
Titles of ORF videos are not being handled properly, as seen in [this mediathek issue](https://github.com/mediathekview/MServer/issues/556). Over there, it apparently has been fixed, but meth does not show the correct titles unfortunately.

Examples:

    meth 'universum >40 station:orf'
    [ORF] Universum: Das könnte Sie auch interessieren: <00:45:54, Sunday, December 8, 2019 at 3:23:47 PM Central European Standard Time>
    [ORF] Universum History: Das könnte Sie auch interessieren: <00:53:43, Friday, December 6, 2019 at 10:35:00 PM Central European Standard Time>

**Comment by Wurzelmann** [comment]
Sorry, about this, this issue has been resolved, like I linked and thus the problem does not occur with any new video list.

**Comment by eikek** [comment]
No worries; I hoped that this is caused by an old movie list when I read it today and good it is resolved that way.
